import Database from 'better-sqlite3';
export declare class SQLiteService {
    private db;
    constructor(dbPath?: string);
    /** @deprecated schema 已迁移到 packages/server/migrations/, 此方法保留为空仅为向前兼容 */
    private initSchema;
    createBatch(batch: {
        batch_id: string;
        recipe_id: string;
        recipe_version: string;
        reactor_id?: string;
        organism?: string;
        operator_id: string;
        total_phases: number;
    }): void;
    private static BATCH_UPDATABLE;
    updateBatch(batchId: string, updates: Record<string, any>): void;
    getBatch(batchId: string): any;
    listBatches(limit?: number, offset?: number, reactorId?: string): any[];
    writeStateTransition(entry: {
        batch_id: string;
        from_state: string;
        to_state: string;
        event: string;
        triggered_by: string;
        phase_id?: string;
        step_number?: number;
        context?: any;
    }): void;
    getStateTransitions(batchId: string): any[];
    writeAuditLog(log: {
        user_id: string;
        action: string;
        target_type: string;
        batch_id?: string;
        target_id?: string;
        old_value?: string;
        new_value?: string;
        reason?: string;
        ip_address?: string;
        trace_id?: string;
    }): void;
    getAuditLogs(batchId?: string, limit?: number): any[];
    createAlarm(alarm: {
        batch_id?: string;
        alarm_code: string;
        severity: string;
        source: string;
        message: string;
        channel?: string;
        pv_at_trigger?: number;
        sv_at_trigger?: number;
    }): number;
    acknowledgeAlarm(id: number, userId: string): void;
    getUnacknowledgedAlarms(batchId?: string): any[];
    writePhaseLog(log: {
        batch_id: string;
        phase_index: number;
        phase_id: string;
        phase_type: string;
        total_steps: number;
        entry_snapshot?: any;
    }): number;
    completePhaseLog(id: number, result: string, completedSteps: number, exitSnapshot?: any): void;
    writeStepLog(log: {
        batch_id: string;
        phase_index: number;
        phase_id: string;
        phase_type: string;
        step_number: number;
        step_name: string;
        elapsed_sec: number;
        result: string;
        condition_actual?: number;
        entry_snapshot?: any;
        exit_snapshot?: any;
    }): void;
    getPhaseLogs(batchId: string): any[];
    getStepLogs(batchId: string, phaseIndex?: number): any[];
    writeCommEvent(event: {
        batch_id?: string;
        connection_id: string;
        event_type: string;
        reason?: string;
        pc_counter?: number;
        plc_counter?: number;
        downtime_s?: number;
        auto_held?: boolean;
    }): void;
    addOfflineSample(sample: {
        batch_id: string;
        sample_time: string;
        sampled_by: string;
        od600?: number;
        dcw_g_L?: number;
        glucose_g_L?: number;
        acetate_g_L?: number;
        product_titer?: number;
        product_unit?: string;
        lactate_g_L?: number;
        biomass_g_L?: number;
        cell_viability_pct?: number;
        ethanol_g_L?: number;
        extra_analytes?: any;
        notes?: string;
    }): void;
    getOfflineSamples(batchId: string): any[];
    createSuggestion(s: {
        batch_id: string;
        suggestion_type: string;
        source_module: string;
        target_param: string;
        current_value?: number;
        suggested_value?: number;
        confidence?: number;
        reasoning?: string;
        expires_at?: string;
    }): number;
    acceptSuggestion(id: number, userId: string): void;
    rejectSuggestion(id: number, userId: string): void;
    expirePendingSuggestions(batchId: string): void;
    getPendingSuggestions(batchId?: string): any[];
    createRecipe(recipe: {
        recipe_id: string;
        version: string;
        name: string;
        author: string;
        target_organism?: string;
        vessel_config: any;
        phases?: any[];
        dag?: any;
        dag_schema_version?: number;
        is_template?: number;
        parent_template_id?: string;
        parent_version?: string;
        created_by: string;
    }): void;
    approveRecipe(recipeId: string, version: string, approvedBy: string): void;
    submitForReview(recipeId: string, version: string): void;
    rejectRecipe(recipeId: string, version: string, reason: string): void;
    listPendingApprovals(): any[];
    countPendingApprovals(): number;
    submitForDeprecation(recipeId: string, version: string): void;
    approveDeprecation(recipeId: string, version: string, approvedBy: string): void;
    rejectDeprecation(recipeId: string, version: string, reason: string): void;
    restoreDeprecated(recipeId: string, version: string): void;
    listPendingReview(): any[];
    getRecipe(recipeId: string, version?: string): any;
    listRecipes(status?: string, opts?: {
        isTemplate?: boolean;
    }): any[];
    listRecipeVersions(recipeId: string): any[];
    getRecipeForDiff(recipeId: string, v1: string, v2: string): {
        v1: any;
        v2: any;
    } | null;
    saveAsTemplate(srcRecipeId: string, srcVersion: string, createdBy: string): {
        template_id: string;
        version: string;
    };
    instantiateTemplate(templateId: string, templateVersion: string, newRecipeId: string, newName: string, createdBy: string): void;
    addCalibration(cal: {
        channel: string;
        sensor_type: string;
        calibrated_by: string;
        cal_point_low_raw?: number;
        cal_point_low_eng?: number;
        cal_point_high_raw?: number;
        cal_point_high_eng?: number;
        do_zero_offset?: number;
        do_slope?: number;
        do_barometric_mbar?: number;
        expires_at?: string;
        notes?: string;
    }): void;
    getLatestCalibration(channel: string): any;
    static readonly REACTOR_CATEGORIES: readonly string[];
    listReactorConfigs(): any[];
    getReactorConfig(reactorId: string): any;
    upsertReactorConfig(config: {
        reactor_id: string;
        name: string;
        description?: string;
        vessel_volume_L?: number;
        plc_connection_id?: string;
        plc_protocol?: string;
        plc_ip?: string;
        plc_port?: number;
        plc_rack?: number;
        plc_slot?: number;
        heartbeat_write?: string;
        heartbeat_read?: string;
        enabled?: number;
        sort_order?: number;
        category?: string;
    }): void;
    deleteReactorConfig(reactorId: string): void;
    static readonly RAW_MATERIAL_CATEGORIES: readonly string[];
    listRawMaterials(opts?: {
        category?: string;
        limit?: number;
        offset?: number;
    }): any[];
    getRawMaterial(materialId: string): any;
    createRawMaterial(m: {
        material_id: string;
        name: string;
        category: string;
        supplier?: string;
        catalog_no?: string;
        unit?: string;
        cost_per_unit?: number;
        storage?: string;
        physical_properties?: any;
        notes?: string;
        created_by?: string;
    }): void;
    updateRawMaterial(materialId: string, patch: Partial<{
        name: string;
        category: string;
        supplier: string;
        catalog_no: string;
        unit: string;
        cost_per_unit: number;
        storage: string;
        physical_properties: any;
        notes: string;
    }>): void;
    softDeleteRawMaterial(materialId: string): void;
    setMsdsFilename(materialId: string, filename: string): void;
    createDoeStudy(study: {
        study_id: string;
        name: string;
        description?: string;
        base_recipe_id?: string;
        base_recipe_version?: string;
        design_type: string;
        factors: any[];
        responses: any[];
        created_by: string;
    }): void;
    listDoeStudies(): any[];
    getDoeStudy(studyId: string): any;
    updateDoeStudyStatus(studyId: string, status: string): void;
    updateDoeStudy(studyId: string, patch: {
        name?: string;
        description?: string;
        factors?: any[];
        responses?: any[];
        design_type?: string;
        base_recipe_id?: string;
        base_recipe_version?: string;
    }): void;
    deleteDoeStudy(studyId: string): void;
    replaceDoeRuns(studyId: string, rows: {
        run_index: number;
        factor_values: any;
    }[]): void;
    listDoeRuns(studyId: string): any[];
    getDoeRun(studyId: string, runIndex: number): any;
    updateDoeRunRecipe(studyId: string, runIndex: number, recipeId: string, recipeVersion: string): void;
    bindDoeRunBatch(studyId: string, runIndex: number, batchId: string): void;
    setDoeRunResponse(studyId: string, runIndex: number, responses: Record<string, number>, notes?: string): void;
    getDatabase(): Database.Database;
    close(): void;
}
//# sourceMappingURL=sqlite-service.d.ts.map