export const FUXA_TO_BIOCORE_TYPE: Record<string, string> = {
  'svg-ext-value': 'svg-label',
  'svg-ext-text': 'svg-label',
  'svg-ext-html_button': 'svg-button',
  'svg-ext-html_switch': 'svg-switch',
  'svg-ext-html_input': 'svg-input',
  'svg-ext-html_select': 'svg-select',
  'svg-ext-html_slider': 'svg-slider',
  'svg-ext-html_image': 'svg-image',
  'svg-ext-html_chart': 'svg-chart',
  'HXT_TANK': 'svg-tank',
  'HXT_PUMP': 'svg-pump',
  'HXT_VALVE': 'svg-valve',
  'HXT_MOTOR': 'svg-motor',
  'HXT_HEATER': 'svg-heater',
  'HXT_REACTOR': 'svg-reactor',
  'HXT_SENSOR': 'svg-sensor',
  'HXT_PROBE': 'svg-probe',
  'HXT_STIRRER': 'svg-stirrer',
  'HXT_SPARGER': 'svg-sparger',
  'HXT_PIPE': 'svg-pipe',
  'HXT_LAMP': 'svg-lamp',
  'HXT_INDICATOR': 'svg-indicator',
  'HXT_GAUGE': 'svg-gauge',
};
