import { readdirSync, writeFileSync } from 'fs';
import { join } from 'path';

const SRC_DIR_DEFAULT = join(__dirname, '../packages/web-ui/src/scada-engine/assets/shapes');
const OUT_FILE_DEFAULT = join(
  __dirname,
  '../packages/web-ui/src/scada-engine/editor/palette/shape-catalog.ts',
);

export function toLabel(id: string): string {
  return id
    .split('-')
    .map((w) => (w.length === 0 ? w : w.charAt(0).toUpperCase() + w.slice(1)))
    .join(' ');
}

export function genCatalog(srcDir: string, outFile: string): { count: number } {
  const files = readdirSync(srcDir)
    .filter((f) => f.endsWith('.svg'))
    .sort();
  const entries = files
    .map((f) => {
      const id = f.replace(/\.svg$/, '');
      return `  { id: ${JSON.stringify(id)}, label: ${JSON.stringify(toLabel(id))}, src: '/scada-shapes/${f}' },`;
    })
    .join('\n');
  const body = `// AUTO-GENERATED by scripts/gen-shape-catalog.ts — do not edit manually.

export interface PaletteShape {
  id: string;
  label: string;
  src: string;
}

export const SHAPE_CATALOG: ReadonlyArray<PaletteShape> = [
${entries}
] as const;
`;
  writeFileSync(outFile, body, 'utf8');
  return { count: files.length };
}

if (require.main === module) {
  const { count } = genCatalog(SRC_DIR_DEFAULT, OUT_FILE_DEFAULT);
  // eslint-disable-next-line no-console
  console.log(`gen-shape-catalog: wrote ${count} shapes to ${OUT_FILE_DEFAULT}`);
}
